FROM gradle:7.4.1-jdk17-alpine AS build
COPY ./. ./netty-ims-client
WORKDIR ./netty-ims-client
RUN gradle bootJar
RUN mv ./build/libs/client-1.0.0.jar /

FROM openjdk:17-alpine
COPY --from=build /client-1.0.0.jar ./netty-ims-client/client-1.0.0.jar
ENTRYPOINT ["java","-jar","/netty-ims-client/client-1.0.0.jar"]
